### ISSUE TITLE
No sources listed in OBS Script Window

### ISSUE THREAD

**Issue by matthewwestfall** [deckerego/tally_obs#11]
On installing Python and getting the framework configured in OBS, after adding the obs_tally_light.py script, the script window shows no sources to assign lights to. Confirmed that the lights are working via the HTML script to find the lights on the network.

Versions:
OS: Windows 10
OBS: 30.1.0
Python: 3.11

![image](https://github.com/deckerego/tally_obs/assets/163373244/2e8ec100-6a16-40ca-bce3-ad27b8fbca7d)

**Comment by deckerego** [comment]
Interesting - that might be a sign that you are using an input source the script isn't familiar with. What types of Video Capture Devices are you using?

**Comment by matthewwestfall** [comment]
Primary video capture input is SDI from a Blackmagic card (something like [these](https://www.blackmagicdesign.com/products/decklink), though I don't have the model immediately available). On top of that, we have some NDI inputs as well that I'd love to use.

**Comment by deckerego** [comment]
Currently the settings script recognizes `av_capture` and `droidcam` devices, not SDI or NDI inputs. I can add that ability however... just need to find out what the source IDs would be. Will see if I can dig those up.

**Comment by deckerego** [comment]
@matthewwestfall - could you check your OBS logs and see if you can find the source reference info for your NDI and SDI devices? If you go to Help -> Log Files -> View Current Log in OBS right after it starts, you should see something like:
```
11:58:16.137: ------------------------------------------------
11:58:16.137: Loaded scenes:
11:58:16.137: - scene 'Camera One':
11:58:16.137:     - source: 'DroidCam OBS' (droidcam_obs)
11:58:16.137:         - monitoring: monitor and output
11:58:16.137: - scene 'Camera Two':
11:58:16.137:     - source: 'Laptop Webcam' (av_capture_input_v2)
11:58:16.137: - scene 'Video Capture':
11:58:16.137:     - source: 'HDMI Video Capture Dongle' (av_capture_input_v2)
11:58:16.137:         - monitoring: monitor and output
11:58:16.137: ------------------------------------------------
```

Let me know what that output looks like and I can add those types as video sources.

**Comment by matthewwestfall** [comment]
@deckerego, for sure. Looks like NDI is "ndi_source", and the SDI source is "decklink-input". That SDI source name aligns with the Blackmagic hardware we're using, and NDI is pretty straight forward.


> 14:03:16.187: - scene 'CAM 1':
> 14:03:16.187:     - source: 'Cam3' (decklink-input)
> 14:03:16.187:         - monitoring: monitor and output
> 14:03:16.187:     - source: 'Cam2' (decklink-input)
> 14:03:16.187:         - monitoring: monitor and output


> 14:03:16.187: - scene 'Cam 3 - Mobile - House':
> 14:03:16.187:     - source: 'Mobile Camera' (ndi_source)

**Comment by deckerego** [comment]
I updated the Python plugin script as https://github.com/deckerego/tally_obs/blob/ndi_sdi_source/scripts/obs_tally_light.py - if you could, download that and replace the script you previously installed. This one should pick up those additional sources.

**Comment by matthewwestfall** [comment]
That mostly did it! I had to a ^ in front of each of the new sources on line 134, and once I reloaded OBS they popped right up. 

`if re.search("^av_capture.*|^droidcam.*|^decklink-input.*|^ndi_source.*", source_id):`

Really, though, appreciate the help here!

**Comment by deckerego** [comment]
Sounds good - added to the latest release.
