### ISSUE TITLE
Trouble running after install

### ISSUE THREAD

**Issue by BigRedProductions** [deckerego/tally_obs#4]
from queue import SimpleQueue
ImportError: cannot import name 'SimpleQueue'

**Comment by deckerego** [comment]
It appears you are running an older version of Python - what version of OBS are you running, and what version of Python is it pointing to?

**Comment by BigRedProductions** [comment]
After a little tinkering I was able to get it to work. I am now having trouble getting TallyPi to work. I get it to install good but when i go to test it out I get nothing. 

>

**Comment by deckerego** [comment]
Okay - if you would like to open an issue in the TallyPi repository with steps to reproduce I can try to help you out. Will close this issue for OBS
